# Generated by Django 2.1.4 on 2018-12-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0002_auto_20181211_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='path_to_photo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
