# Generated by Django 2.1.4 on 2018-12-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0003_auto_20181213_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path_to_photo',
        ),
    ]
